server:
  port: 8081
spring:
  application:
    name: hello-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}