spring:
  application:
    name: zuul
server:
  port: 5555
zuul:
  routes:
    api-a:
      path: /api-a/ext/**
      serviceId: hello-service
      sensitiveHeaders:
    api-b:
      path: /api-b/**
#      zuul本地转发
      url: forward:/
#  zuul在路由转发前为请求设置host头信息
  add-host-header: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/