spring:
  application:
    name: feign-consumer
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
      instance-id: ${spring.application.name}:${server.port}