server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhangt1/spingcloud/
          searchPaths: hello-service
          username: zhangt1
          password: zhangtao02103236
    bus:
      enabled: true

  #设置rabbitmq的配置信息
  rabbitmq:
      host: localhost
      port: 5672
      username: springcloud
      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
      instance:
          instance-id: ${spring.application.name}:${server.port}


security:
  basic:
    enabled: true
  user:
    name: root
    password: root


#去掉安全认证
management:
  security:
    enabled: false
