server:
  port: 9101
spring:
  application:
    name: trace-1
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: admin
  sleuth:
    sampler:
      percentage: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}